# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - monitor.den:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - localhost:9090

  - job_name: 'node'
    static_configs:
      # Bare metal
      - targets:
        - dogee.data.den:9100
        - drolf-rpi.data.den:9100
        - rpi-k8s-01.data.den:9100
        - rpi-k8s-02.data.den:9100
        - rpi-k8s-03.data.den:9100
        - rpi-lxd-01.data.den:9100
        - rpi-lxd-02.data.den:9100
        labels:
          group: hw
      # Remote VMs
      - targets:
        - 'tigerfox.isgeek.info:9273'
        labels:
          group: vm
      # LXC containers
      - targets:
        - build.data.den:9100
        - dns-01.data.den:9100
        - dns-02.data.den:9100
        - docker.data.den:9100
#        - kodi.data.den:9100
        - mediabox.data.den:9100
        - monitor.data.den:9100
        - nas.data.den:9100
        - pihole-01.data.den:9100
        - pihole-02.data.den:9100
        - prolink-overlay.data.den:9100
        - puppet5.data.den:9100
        - puppet-01.data.den:9100
        - puppet-02.data.den:9100
        - smtp.data.den:9100
        - torrent.data.den:9100
        labels:
          group: lxd
    metric_relabel_configs:
      - source_labels: [instance]
        regex: '(.+)\.data\.(.+):\d+'
        replacement: '$1.$2'
        target_label: fqdn

  - job_name: 'pihole'
    static_configs:
      - targets:
        - pihole-01.data.den:9617
        - pihole-02.data.den:9617
    metric_relabel_configs:
      - source_labels: [instance]
        regex: '(.+)\.data\.(.+):\d+'
        replacement: '$1.$2'
        target_label: fqdn
      - regex: 'hostname'
        action: labeldrop

  # Blackbox monitoring

  - job_name: 'blackbox-ping'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        # VLAN 20
        - 10.7.20.1  # router.mgmt.den
        - 10.7.20.2  # switch.mgmt.den
        - 10.7.20.3  # cap1.mgmt.den
        - 10.7.20.4  # mikrotik-test.mgmt.den
        - 10.7.20.5  # switch-poe.mgmt.den
        # VLAN gateways
        - 10.7.21.1
        - 10.7.30.1
        - 10.7.31.1
        - 10.7.32.1
        - 10.7.40.1
        - 10.7.41.1
        - 10.7.42.1
        - 10.7.43.1
        - 10.7.44.1
        - 10.7.45.1
        # Bare metal
        - 10.7.20.11  # dogee.mgmt.den
        - 10.7.20.12  # drolf-rpi.mgmt.den
        - 10.7.20.13  # rpi-k8s-01.mgmt.den
        - 10.7.20.14  # rpi-k8s-02.mgmt.den
        - 10.7.20.15  # rpi-k8s-03.mgmt.den
        - 10.7.20.16  # rpi-lxd-01.mgmt.den
        - 10.7.20.17  # rpi-lxd-02.mgmt.den
        # LXCs
        - 10.7.31.21  # build.den
        - 10.7.30.33  # dns-01.den
        - 10.7.30.34  # dns-02.den
        - 10.7.32.14  # docker.den
#        - 10.7.32.18  # kodi.den
        - 10.7.31.19  # mediabox.den
        - 10.7.31.13  # monitor.den
        - 10.7.31.15  # nas.den
        - 10.7.32.30  # pihole-01.den
        - 10.7.32.31  # pihole-02.den
        - 10.7.31.16  # prolink-overlay.den
        - 10.7.30.23  # puppet-01.den
        - 10.7.30.24  # puppet-02.den
        - 10.7.32.17  # smtp.den
        - 10.7.31.20  # torrent.den
        # VIPs
        - 10.7.30.22  # puppet.den
        # Connect Plus
        - 10.230.7.161  # router in the building
        # Public
        - 1.1.1.1
        - 9.9.9.9
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        # .den services
        - http://home-assistant.den
        - http://monitor.den
        - http://mediabox.den
        - http://torrent.den
        - http://pihole-01.den
        - http://pihole-02.den
        # Public
        - https://google.cz
        - https://google.com
        - https://proton.me
        - https://seznam.cz
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: 'snmp'
    metrics_path: /snmp
    params:
      module: [mikrotik]
    static_configs:
      - targets:
        # intentionally no DNS
        - 10.7.21.1
        - 10.7.21.2
        - 10.7.21.3
        - 10.7.21.4
        - 10.7.21.5
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116

  - job_name: 'apcupsd'
    static_configs:
      - targets:
        - drolf-rpi.data.den:9162
    metric_relabel_configs:
      - source_labels: [instance]
        regex: '(.+)\.data\.(.+):\d+'
        replacement: '$1.$2'
        target_label: fqdn
