default:
  walk:
  - 1.3.6.1.2.1.1.3
  - 1.3.6.1.2.1.2.2.1.2
  - 1.3.6.1.2.1.31.1.1.1.6
  - 1.3.6.1.2.1.31.1.1.1.10
  metrics:
  - name: sysUpTime
    oid: 1.3.6.1.2.1.1.3
    type: gauge
  - name: ifHCInOctets
    oid: 1.3.6.1.2.1.31.1.1.1.6
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
  - name: ifHCOutOctets
    oid: 1.3.6.1.2.1.31.1.1.1.10
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
