## Puppet managed

uid = nobody
gid = nobody
use chroot = no
max connections = 4
syslog facility = daemon
pid file = /run/rsyncd.pid

[rootfs]
	path = /
	comment = root fs
	uid = root
	gid = root
	read only = yes
	list = yes
	auth users = backup
	secrets file = /etc/rsyncd.secrets
	hosts allow = dogee.data.den
