groups:
  - name: system
    rules:
      - alert: LowUptime
        expr: time() - instance:system_uptime < 3600
        for: 35m
        annotations:
          summary: "Node {{ $labels.instance }} encountered a reboot in past 1 hour"
      - alert: NodeDown
        expr: up{job="node"} == 0
        for: 5m
        annotations:
          summary: "Node {{ $labels.instance }} down for more than 5 minutes"
      - alert: LoadHigh
        expr: instance:load5_to_cpu_ratio > 1.5
        for: 1m
        annotations:
          summary: "Load of node {{ $labels.instance }} is high"
#      - alert: RootFSGettingFull
#        expr: instance:rootfs_free_percent < 0.20
#        annotations:
#          summary: "Root filesystem on node {{ $labels.instance }} is getting full ({{ $value }} % free)"
      - alert: RootFSGettingFull
        expr: instance:rootfs_free_bytes < 1024*1024*1024
        annotations:
          summary: "Root filesystem on node {{ $labels.instance }} is getting full ({{ $value }} bytes free)"
      - alert: CPUUsageHigh
        expr: instance:cpu_usage_percent5m > 90
        for: 2m
        annotations:
          summary: "CPU usage on node {{ $labels.instance }} is high ({{ $value }} %)"
      - alert: PuppetNotUpdated
        expr: time() - puppet_last_run > 3600
        annotations:
          summary: "Puppet agent on node {{ $labels.instance }} hasn't applied the catalog for over 1 hour"
      - alert: EximLocalMaildirNotEmpty
        expr: exim4_local_maildir_size > 0
        annotations:
          summary: "Local Exim4 maildir on node {{ $labels.instance }} is not empty"
  # Imported from https://awesome-prometheus-alerts.grep.to/rules#zfs
  # FIXME: Too old kernel I guess
#  - name: zfs
#    rules:
#      - alert: ZfsOfflinePool
#        expr: node_zfs_zpool_state{state!="online"} > 0
#        for: 1m
#        labels:
#          severity: critical
#        annotations:
#          summary: ZFS offline pool (instance {{ $labels.instance }})
#          description: "A ZFS zpool is in a unexpected state: {{ $labels.state }}.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
